### ISSUE TITLE
変数の使い方

### ISSUE THREAD

**Issue by pipopixu** [c0b21055/ProjExD#11]
https://github.com/c0b21055/ProjExD/blob/38a434ff376e20633d813925905da6dd2617fbd0/ex4/dodge_bom.py#L46

爆弾の色をランダムにするために変数を三つ作ったのだと思うのですが、これらの変数をどこでどのように使っているのかが分かりませんでした。コードの行数をコメントアウトなどで具体的に示していただきたいです。

**Comment by c0b21055** [comment]
ありがとうございます。
