### ISSUE TITLE
何の変数なのかわかりやすくする

### ISSUE THREAD

**Issue by c0b21125** [c0b21055/ProjExD#2]
https://github.com/c0b21055/ProjExD/blob/1b9ed1c2c465a56ab1efd37a7a9641dcadc350c8/ex01/alphabet.py#L6

変数名がすべてcha〇となっていて、コードを読み返すときに何を意味する変数なのかが分かりにくいので、意味のある変数名にした方が分かりやすいと思う。

**Comment by c0b21055** [comment]
ありがとうございます。
参考にします。
