### ISSUE TITLE
バックとは？

### ISSUE THREAD

**Issue by c0b21125** [c0b21055/ProjExD#4]
https://github.com/c0b21055/ProjExD/blob/a44edf671bc0894834efd264d91493b4c2b04f27/ex2/calc1.py#L55

バックという機能は、一文字消去という認識であっていますか？あまり聞かない名前の機能だったので疑問に思いました。

**Comment by c0b21055** [comment]
はい、その認識であっています。
一文字一文字消えていく機能です。
