### ISSUE TITLE
コードの説明について

### ISSUE THREAD

**Issue by pipopixu** [c0b21055/ProjExD#5]
https://github.com/c0b21055/ProjExD/blob/a44edf671bc0894834efd264d91493b4c2b04f27/ex2/calc1.py#L60

処理についてコメントアウトを見ても何を何の為にしているのかよく分かりませんでした。
何を入れ替えるのかを分かりやすく言葉を足せるといいと思います。

**Comment by c0b21055** [comment]
確かに、ネットの記事を引用したものなので、調べておきます。
