### ISSUE TITLE
コードの意味

### ISSUE THREAD

**Issue by c0b21125** [c0b21055/ProjExD#6]
https://github.com/c0b21055/ProjExD/blob/a44edf671bc0894834efd264d91493b4c2b04f27/ex2/calc1.py#L60

ボタンを押したときの条件分岐で、記号の場合入れ替えるという操作があるが、何と何を入れ替えるのかが不明瞭でこの操作の必要性が分からない。

**Comment by c0b21055** [comment]
ネットのやり方の引用なので、調べておきます。
